# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField(unique=True)),
                ('cbsa', models.IntegerField()),
                ('cbsa_title', models.CharField(max_length=255)),
                ('monthly_rent', models.FloatField()),
                ('nightly_rev', models.FloatField()),
                ('payoff_nights', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
