# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20160811_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='monthly_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='nightly_rev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='payoff_nights',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
